# Feature Selection Method Based on Grey Wolf Optimization for Coronary Artery Disease Classification

In [1]:
import random
import time
import math
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import benchmarks

data = pd.read_csv("cleavland.csv")
data.head()

c:\Users\asus\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,AGE,SEX,CP,TRESTBPS,CHOL,FBD,REST ECG,THALACH,EXANG,OLDPEAK,SLOPE,CA,THAL,RESULT
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0

### Data preprocessing, extraction and splitting

In [2]:
X = data.iloc[:,:13].values
Y = data['RESULT'].values
print(X.shape)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40, random_state = 14)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

(303, 13)

### Applying SVM classification without data processing

In [3]:
svcclassifier = SVC(kernel = 'poly', random_state = 50)
svcclassifier.fit(X_train, y_train)
y_pred = svcclassifier.predict(X_test)
P = accuracy_score(y_pred,y_test)
print("Accuracy score for SVM:",P)

Accuracy score for SVM: 0.5983606557377049

### GWO Optimization algo

In [4]:
def GWO(objf,lb,ub,dim,SearchAgents_no,Max_iter):
    
    # initialize alpha, beta, and delta_pos
    Alpha_pos=np.zeros(dim)
    Alpha_score=float("inf")
    
    Beta_pos=np.zeros(dim)
    Beta_score=float("inf")
    
    Delta_pos=np.zeros(dim)
    Delta_score=float("inf")

    if not isinstance(lb, list):
        lb = [lb] * dim
    if not isinstance(ub, list):
        ub = [ub] * dim
    
    #Initialize the positions of search agents
    Positions = np.zeros((SearchAgents_no, dim))
    for i in range(dim):
        Positions[:, i] = np.random.uniform(0,1, SearchAgents_no) * (ub[i] - lb[i]) + lb[i]
    
    Convergence_curve=np.zeros(Max_iter)

     # Loop counter
    print("GWO is optimizing  \""+objf.__name__+"\"")    

    # Main loop
    for l in range(0,Max_iter):
        for i in range(0,SearchAgents_no):
            
            # Return back the search agents that go beyond the boundaries of the search space
            for j in range(dim):
                Positions[i,j]=np.clip(Positions[i,j], lb[j], ub[j])

            # Calculate objective function for each search agent
            fitness=objf(Positions[i,:])
            
            # Update Alpha, Beta, and Delta
            if fitness<Alpha_score :
                Alpha_score=fitness; # Update alpha
                Alpha_pos=Positions[i,:].copy()
            
            
            if (fitness>Alpha_score and fitness<Beta_score ):
                Beta_score=fitness  # Update beta
                Beta_pos=Positions[i,:].copy()
            
            
            if (fitness>Alpha_score and fitness>Beta_score and fitness<Delta_score): 
                Delta_score=fitness # Update delta
                Delta_pos=Positions[i,:].copy()
        
        a=2-l*((2)/Max_iter); # a decreases linearly fron 2 to 0
        
        # Update the Position of search agents including omegas
        for i in range(0,SearchAgents_no):
            for j in range (0,dim):     
                           
                r1=random.random() # r1 is a random number in [0,1]
                r2=random.random() # r2 is a random number in [0,1]
                
                A1=2*a*r1-a; # Equation (3.3)
                C1=2*r2; # Equation (3.4)
                
                D_alpha=abs(C1*Alpha_pos[j]-Positions[i,j]); # Equation (3.5)-part 1
                X1=Alpha_pos[j]-A1*D_alpha; # Equation (3.6)-part 1
                           
                r1=random.random()
                r2=random.random()
                
                A2=2*a*r1-a; # Equation (3.3)
                C2=2*r2; # Equation (3.4)
                
                D_beta=abs(C2*Beta_pos[j]-Positions[i,j]); # Equation (3.5)-part 2
                X2=Beta_pos[j]-A2*D_beta; # Equation (3.6)-part 2       
                
                r1=random.random()
                r2=random.random() 
                
                A3=2*a*r1-a; # Equation (3.3)
                C3=2*r2; # Equation (3.4)
                
                D_delta=abs(C3*Delta_pos[j]-Positions[i,j]); # Equation (3.5)-part 3
                X3=Delta_pos[j]-A3*D_delta; # Equation (3.5)-part 3             
                
                Positions[i,j]=(X1+X2+X3)/3  # Equation (3.7)        
        Convergence_curve[l]=Alpha_score;

        #if (l%1==0):
               #print(['At iteration '+ str(l)+ ' the best fitness is '+ str(Alpha_score)]);
    
    print(Positions.shape)
    print("Alpha position=",Alpha_pos);
    print("Beta position=",Beta_pos);
    print("Delta position=",Delta_pos);
    return Alpha_pos,Beta_pos;

### Setting GWO parameters

In [5]:
iters=100
wolves=5
dimension=13
search_domain=[0,1]
lb=-1.28
ub=1.28
colneeded=[0,1,2,4,5,7,8,10,11]
modified_data=pd.DataFrame()
for i in colneeded:
    modified_data[data.columns[i]]=data[data.columns[i]].astype(float)
func_details=benchmarks.getFunctionDetails(6)

for i in range(0,10):
    alpha,beta=GWO(getattr(benchmarks,'F7'),lb,ub,dimension,wolves,iters)

GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.01779236  0.11658362  0.08580658 -0.09747281 -0.10514813 -0.13390837
  0.02106524  0.0216336   0.08687137 -0.15234753  0.04999521  0.00191522
 -0.18494057]
Beta position= [-0.01705799  0.110957    0.0873013  -0.1044995  -0.13078831 -0.13482537
  0.0195706   0.02417723  0.07678404 -0.15080467  0.05045137  0.00145967
 -0.18950092]
Delta position= [-0.01693238  0.10867137  0.06887691 -0.0863015  -0.08294455 -0.13311015
  0.02019048  0.02617916  0.10378849 -0.1564553   0.05676222  0.00221294
 -0.22001111]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [ 0.21582375 -0.21529695  0.02971087  0.26397038  0.02613939  0.19470166
 -0.24891373  0.08335149 -0.12323252  0.07986403  0.14031279  0.02431483
  0.15755107]
Beta position= [ 0.11645507 -0.26001392  0.03093091  0.25615207  0.04128209  0.21422675
 -0.19451649  0.09060821 -0.10862266  0.04661628  0.11972298  0.02135011
  0.2302717 ]
Delta position= [ 0.1497137  -0.24010311  0.02978979  0.26917165  0.03527926  0.21214594
 -0.19761979  0.08762661 -0.11706576  0.06629283  0.1375716   0.02338533
  0.19260308]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.22199817 -0.06902002  0.03255992  0.09295499  0.14366049 -0.10448531
 -0.12776776 -0.09053307 -0.02335292  0.12982124  0.0431796   0.06813354
 -0.02070478]
Beta position= [-0.24581216 -0.06739673  0.03206868  0.07515496  0.14255862 -0.10070922
 -0.12850372 -0.09197852 -0.02431999  0.13274096  0.05082776  0.0784745
 -0.02290205]
Delta position= [-0.2256962  -0.06967193  0.03188141  0.08324376  0.14506603 -0.09649605
 -0.12954139 -0.08902849 -0.02397883  0.12702594  0.0498872   0.07595489
 -0.02200654]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.09498142  0.22953831 -0.05995881 -0.20623726  0.15952063  0.11625613
  0.06561473 -0.0654447   0.11982987  0.07792399 -0.04139081  0.03171303
 -0.00993122]
Beta position= [-0.08724904  0.23999582 -0.06421062 -0.22478983  0.18354496  0.10865948
  0.14820222 -0.05886824  0.11217679  0.06048399 -0.03868529  0.03435993
 -0.00950833]
Delta position= [-0.10420059  0.22703269 -0.05607645 -0.23322382  0.16759063  0.12405316
  0.15310636 -0.06225321  0.11615774  0.06788912 -0.04383943  0.03451535
 -0.00991426]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.22332846 -0.08947342 -0.03686299 -0.05560426 -0.03375617  0.01888539
  0.053152   -0.03386321  0.01637424  0.08435059 -0.07630658  0.15320661
 -0.15374816]
Beta position= [-0.25815012 -0.13787822 -0.04735774 -0.06902043 -0.03156546  0.01998783
  0.03451028 -0.04523793  0.02464962  0.09352586 -0.05045527  0.16613916
 -0.17215597]
Delta position= [-0.2159978  -0.09891325 -0.03831927 -0.06138069 -0.03368046  0.02377523
  0.05562959 -0.04410216  0.02240492  0.0756365  -0.05930647  0.1342461
 -0.17025481]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.12698607 -0.06783973 -0.05358099  0.27731356  0.00169043  0.15628793
  0.03450258  0.01896355  0.07170703  0.19312606 -0.0319821   0.13066253
 -0.10641257]
Beta position= [-0.12702846 -0.0642695  -0.04918796  0.24358004  0.0043118   0.15041248
  0.03058097  0.01990146  0.06115859  0.21132038 -0.03107669  0.12632348
 -0.11085559]
Delta position= [-0.11878043 -0.05825546 -0.04691896  0.20586132  0.00542052  0.14228481
  0.02610247  0.02181956  0.05433413  0.23104213 -0.02633222  0.1203101
 -0.12156766]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [ 0.02418908  0.12268802  0.14816864 -0.10617404  0.0113665   0.06361526
 -0.04141507 -0.05579323 -0.11999097 -0.09140553  0.18230922  0.01998698
  0.00598466]
Beta position= [ 0.02789879  0.14372945  0.15951484 -0.12283483  0.01358684  0.064684
 -0.03935875 -0.06063899 -0.13850295 -0.08847139  0.19956304  0.02214081
  0.00490101]
Delta position= [ 0.0279799   0.14436157  0.15823532 -0.12148531  0.01331702  0.06441424
 -0.0390233  -0.06047098 -0.13766679 -0.08828655  0.20008553  0.02189377
  0.00492673]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [ 0.2621547   0.08633153 -0.21192462 -0.08409828 -0.10965337  0.0464848
 -0.04116994  0.05228742 -0.01055439 -0.05873862 -0.08595213 -0.04974985
  0.01400496]
Beta position= [ 0.23281982  0.08408445 -0.17004341 -0.09247111 -0.11597447  0.05217884
 -0.0364146   0.04871117 -0.01201821 -0.05437377 -0.09007058 -0.05192853
  0.01451917]
Delta position= [ 0.19702295  0.07609275 -0.16144141 -0.09230225 -0.1244645   0.04762886
 -0.03490425  0.04509577 -0.0121658  -0.06150105 -0.08108422 -0.05651702
  0.01564226]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.11890208  0.11342124  0.09818905  0.00591722 -0.12656088  0.0522108
  0.14303186  0.0343397  -0.17384228  0.04836732  0.18017498 -0.08806984
  0.09890946]
Beta position= [-0.11114239  0.11308433  0.09983245  0.00606094 -0.12631578  0.05290056
  0.14339925  0.03496612 -0.17098415  0.05023402  0.17944006 -0.08828563
  0.10345481]
Delta position= [-0.10872909  0.11832624  0.10202934  0.00634466 -0.10580853  0.04962625
  0.15567294  0.03980156 -0.17419177  0.05080741  0.17883152 -0.08803843
  0.10613567]
GWO is optimizing  "F7"
(5, 13)
Alpha position= [-0.0011091   0.01247821  0.16629694  0.13606646  0.09286021 -0.09494759
  0.01002442 -0.02090755  0.13394611 -0.08926302 -0.14659294  0.05815742
  0.04866019]
Beta position= [-0.00115305  0.01378385  0.14275693  0.15981209  0.0925009  -0.0894825
  0.00845528 -0.02135575  0.1372627  -0.07697394 -0.1605408   0.07729788
  0.03202689]
Delta position= [-0.00118365  0.01218873  0.13996127  0.17148751  0.08289117 -0.10513278
  0.01145896 -0.02336932  0.13569831 -0.05453172 -0.16307182  0.08126447
  0.03079334]

In [6]:
##Applying feature selection on the given dataset
##considering alpha as best solution and putting a threshold
threshold=-0.05
index=[]
print("alpha shape=",alpha.shape[0])
modified_daata=pd.DataFrame();
for i in range(0,alpha.shape[0]):
    if(alpha[i]>=threshold):
        modified_daata[data.columns[i]]=data[data.columns[i]].astype(float)
print("The modified data is following")
modified_daata.head()

alpha shape= 13
The modified data is following

    AGE  SEX   CP  TRESTBPS   CHOL  REST ECG  THALACH  EXANG   CA  THAL
0  63.0  1.0  1.0     145.0  233.0       2.0    150.0    0.0  0.0   6.0
1  67.0  1.0  4.0     160.0  286.0       2.0    108.0    1.0  3.0   3.0
2  67.0  1.0  4.0     120.0  229.0       2.0    129.0    1.0  2.0   7.0
3  37.0  1.0  3.0     130.0  250.0       0.0    187.0    0.0  0.0   3.0
4  41.0  0.0  2.0     130.0  204.0       2.0    172.0    0.0  0.0   3.0

### Applying svm on the modified data

In [7]:
Y = data['RESULT'].values
X_train, X_test, y_train, y_test = train_test_split(modified_daata, Y, test_size = 0.40, random_state = 14)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train[0])
modified_daata.info()

[-0.37086712  0.6520712  -0.1543891  -1.21573705 -1.45429374 -0.9863518
 -1.07775066 -0.76662853 -0.77346436 -0.95367089]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   AGE       303 non-null    float64
 1   SEX       303 non-null    float64
 2   CP        303 non-null    float64
 3   TRESTBPS  303 non-null    float64
 4   CHOL      303 non-null    float64
 5   REST ECG  303 non-null    float64
 6   THALACH   303 non-null    float64
 7   EXANG     303 non-null    float64
 8   CA        303 non-null    float64
 9   THAL      303 non-null    float64
dtypes: float64(10)
memory usage: 23.8 KB

In [8]:
svcclassifier = SVC(kernel = 'rbf', random_state = 50)
svcclassifier.fit(X_train, y_train)
y_pred = svcclassifier.predict(X_test)
P1=accuracy_score(y_pred,y_test)
print("Modified Accuracy score for SVM:", P1)
print("Earlier Accuracy score was", P)

Modified Accuracy score for SVM: 0.6147540983606558
Earlier Accuracy score was 0.5983606557377049